### ISSUE TITLE
Can not save if multiple addresses separated by a comma

### ISSUE THREAD

**Issue by AlainRnet** [bascherz/Content-Notifier-Joomla-Plugin#1]
Hello.
Thank you for your plugin.
In field To, I want to write more than one adress and when I type a comma, the border field become red ans I cannot save the plugin despite the mention of separating the addresses by a comma.

https://github.com/bascherz/Content-Notifier-Joomla-Plugin/blob/422e6487aec8db40812d32890de9a9bc441ceaaa/src/notifiergroup.xml#L16

Many thanks in advance for your help.

**Comment by bascherz** [comment]
Hello,

I added the email validation after implementing the multi-address feature. 
If you simply delete the line in the XML file that has validate=email and 
you should be golden.

Bruce

**Comment by AlainRnet** [comment]
Many thanks for your answer.

I removed line 18 from the XML file but unfortunately I still can not
validate multiple addresses and the edge of the field is still red.

**Comment by bascherz** [comment]
Ok. I'm on vacation in Europe. It'll have to wait until I get home. Sorry. 
No computer on this trip.

Bruce

**Comment by AlainRnet** [comment]
No problem!
Many thanks for your answers despite being on vacation!

You can stil come here in Switzerland ;-)

**Comment by bascherz** [comment]
Currently on a river cruise ship between Durnstein and Melk, Austria. 
Beautiful Wachau Valley. :-)

**Comment by bascherz** [comment]
Hi Alain,

Finally home and getting around to things like this. Here’s what I discovered.

Here is what the XML currently looks like (in notifiergroup.xml):


In order to allow a comma-separated list of addresses, you need to make it look like this:


In addition to removing the line validate=”email”, which I suggested while on my vacation, you also have to change the field type from “email” to “text”.

I will probably make a note of this in the wiki page of the plugin since I suspect some people will prefer to use an email list system instead of a list of addresses. I may end up making these changes to the plugin itself and suggesting how to make Joomla validate the address for you. Unfortunately, there is no “emails” field type. That would be nice. 😊

Thanks for bringing this to my attention and enjoy the plugin.

Cheers,
Bruce
________________________________________________
Bruce Scherzinger * bruce.scherzinger@gmail.com

**Comment by bascherz** [comment]
Released Version 2.3, which implements the XML changes suggested in this email discussion, thus removing email address field validation and again allowing comma-separated list of addresses. Note that no validation of this field is done now.

**Comment by AlainRnet** [comment]
Thank you very much!!
